# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Update prices

on:
  schedule:
    - cron: 0 4 * * *

jobs:
  all:
    name: Update prices
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build --tag=dg_updater updater/

      - name: Update prices
        run: docker run --env=GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} dg_updater
